on: 
  release:
    types: [created]
  
name: Release
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release binaries
      uses: mcuadros/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
        ldflags: -X main.commit=${{ github.sha }} -X main.version=${{ github.ref }}